# generate calls the ygot generator to generate Go code from 
# all YANG modules. The generator name will be overridden in the
# generated code using sed. 
generate:
	~/go/bin/go1.24.0 tool github.com/openconfig/ygot/generator -path=yang -output_file=pkg/mudyang/mudyang.go -generate_simple_unions -package_name=mudyang -generate_fakeroot -fakeroot_name=mudfile yang/ietf-packet-fields@2019-03-04.yang yang/ietf-ethertypes@2019-03-04.yang yang/ietf-acldns.yang yang/ietf-access-control-list@2019-03-04.yang yang/ietf-inet-types@2024-10-21.yang yang/iana-tls-profile@2025-04-18.yang yang/ietf-acl-tls@2025-04-18.yang yang/iana-hash-algs.yang yang/ietf-netconf-acm.yang yang/ietf-crypto-types@2021-09-14.yang yang/ietf-mud-transparency@2023-10-10.yang yang/ietf-ol@2024-04-26.yang yang/ietf-mud-tls@2025-04-18.yang yang/ietf-mud@2019-01-28.yang
	sed '7s,.*,This package was generated by github.com\/openconfig\/ygot\/generator@v0.31.0,g' pkg/mudyang/mudyang.go > pkg/mudyang/mudyang.go.rewritten && mv pkg/mudyang/mudyang.go.rewritten pkg/mudyang/mudyang.go

.PHONY: generate